version: '2'
services:
  master_jenkins:
    build: .
    container_name: 'master_jenkins'
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins_data:/bitnami/jenkins'
    networks:
      - 'abcd'
  redis_server:
    image: 'redis'
    container_name: 'redis_server'
    ports:
      - '6060:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - 'abcd'
          
volumes:
  jenkins_data:
    driver: local
  redis_data:
    driver: local
networks:
  abcd:
    driver: bridge
