version: '2'
services:
  master_jenkins:
    build: .
    container_name: 'master_jenkins'
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins_data:/bitnami/jenkins'

volumes:
  jenkins_data:
    driver: local
